spring:
  application.name: project-reactor-example
  r2dbc:
    url: r2dbc:h2:mem:///test2db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:db.init/schema.sql